apiDir: "../data-engine-rest-api/src/main/java"
apiPackagePath: "com.liferay.data.engine.rest"
application:
    baseURI: "/data-engine"
    className: "DataEngineRESTApplication"
    name: "Liferay.Data.Engine.REST"
author: "Jeyvison Nascimento"
clientDir: "../data-engine-rest-client/src/main/java"
forcePredictableOperationId: true
testDir: "../data-engine-rest-test/src/testIntegration/java"