apiDir: "../search-experiences-rest-api/src/main/java"
apiPackagePath: "com.liferay.search.experiences.rest"
application:
    baseURI: "/search-experiences-rest"
    className: "SearchExperiencesRESTApplication"
    name: "Liferay.Search.Experiences.REST"
author: "Brian Wing Shun Chan"
clientDir: "../search-experiences-rest-client/src/main/java"
forcePredictableOperationId: true
testDir: "../search-experiences-rest-test/src/testIntegration/java"