apiDir: "../sample-api/src/main/java"
apiPackagePath: "com.example.sample"
application:
    baseURI: "/sample"
    className: "SampleApplication"
    name: "sample-application"
    security:
        basicAuth: true
        guestAllowed: true
        oAuth2: true
author: "John Doe"